INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Daily every', 'Sick foot brain express truth sure written exclaimed entire ability next treated store coast tail kept coast sheet symbol zulu gradually season southern oxygen than appropriate title see work making draw plates canal contrast whom page five rocky evidence operation active steam yesterday hurt earlier movement branch dig some light peace parent fighting driving memory variety final replace catch monkey born shape brush brown fewer wore duty show direct mood quarter spread opportunity salmon paint cool school blew mail toy about thrown pond bottom burst gasoline taught driver great tropical is brother human hurried truck top tin nodded skin breathe world fat than dust origin slow dust tired harder summer point underline sides equal birthday dig brass around me lungs to tent word definition fair equator grow seems duck feathers examine song ten direction ', 1, 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg', 'https://images.pexels.com/photos/2088258/table-dining-room-chair-dining-area-2088258.jpeg?auto=compress&cs=tinysrgb&h=350', 2438, 1000, 2, 1, '2023-07-13', true, 'Prince Edward Island', 'Charlottetown', 'Canada', '1716 Misih Highway', '48752');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Magic familiar', 'Comfortable fill stick belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring ', 1, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1200, 3, 0, '2023-08-16', true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'List least', 'Younger week student surface speak how sick bark outside combine wide thou improve recent plane soon behavior teacher tape adult pencil remain bear laugh free spin make stick victory picture wheat successful near correctly swept steep lake chapter card film telephone identity brick lucky electricity solar captain rest surprise worth folks caught example larger headed sugar symbol represent handle dot spell straw barn plate among party long fix fifteen had show chain way religious rest afternoon bat accurate behavior bigger term exact hang without him garden yet fur spirit cut bright money plus eight birthday composition soil she minute industrial silk hair herd chief silence temperature thought teacher show signal eye grew deal conversation tank castle energy empty cast carbon care western climate zipper cloth moving lovely shot brush angry ready ', 2, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 34565, 800, 1, 1, '2022-11-17', true, 'Newfoundland And Labrador', 'Paradise', 'Canada', '1848 Cuzo Trail', '08409');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Done game', 'Invented friendly longer circle agree today yet family trunk yard door noted chemical struck queen grandmother shelf at state command zulu from proper spoken powerful closely throat ability field went beside thought seat rock offer partly fair smooth announced even news carried habit film shells complex outer driven track are flag wise eager explain feature boy active proud thank writing due native last reason camera settle piece melted won draw was bark foreign given catch law minerals climb break mail force dawn pie rule simplest offer chance jump gold correctly lucky hit chemical new island start like gas loud create general group simple difficulty action back bean spend for telephone gentle there page tape position chapter oil tea fact sugar jungle receive ride poor join today soap belt jungle many wonderful difficulty swung cannot sale wear apartment gulf remove fresh somebody art hole third wash exercise jet development for giving health front knife underline source catch meat recent fifty band apartment father human bank shaking film education oxygen return greatly ', 2, 'https://images.pexels.com/photos/271649/pexels-photo-271649.jpeg', 'https://images.pexels.com/photos/271649/pexels-photo-271649.jpeg?auto=compress&cs=tinysrgb&h=350', 57597, 5000, 1, 7, '2022-10-25', true, 'Prince Edward Island', 'Summerside', 'Canada', '1624 Cufpip Square', '79224');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Prepare if', 'Angry pair does flame factory night sum party trip tomorrow none friend rain quickly generally grew bell row my stairs turn sang possibly having badly over bit inside six industry lonely scientific use he only as long feel instrument worth struggle almost material pilot good roar raw past chief describe join parts welcome feed figure trip settlers partly egg happily have forth bad percent join tobacco writing harder dream series shaking nuts wrong trap actual electric limited join deal hand tape know serve divide sky everyone we snow save mill engineer declared tea proper again earlier strange away aid yet total capital regular pride dream tape example hidden both sense possible earn increase environment area join sand pleasant made hungry throat safety such fighting fruit molecular event ', 3, 'https://images.pexels.com/photos/977739/pexels-photo-977739.jpeg', 'https://images.pexels.com/photos/977739/pexels-photo-977739.jpeg?auto=compress&cs=tinysrgb&h=350', 21137, 2300, 7, 2, '2022-11-07', true, 'Ontario', 'Orillia', 'Canada', '1492 Ufimo Junction', '47597');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Roll stranger', 'Observe typical hit organization fruit thumb cost beat numeral chest careful character lose far tent meant thrown traffic movie use golden receive brain rod mood wooden children solve swung though spider smell box put importance afraid touch above smile would refer size good correctly blue duck hunt divide lack whenever further thus organization reach frozen furniture river claws threw catch uncle gray meant lips shout sister pack want trade active wrong value store plural alphabet to police agree make why honor decide rhyme rough new sale come putting remove noted castle object window bridge complete steam sort process opportunity replace basis method hour pine duty inside electricity think surprise go rice nearer fewer hearing soil bite water higher active continent solve beside muscle seeing develop general prize atom musical unusual active appearance cost bean structure zero bus series grew station word organization complete ', 3, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 5375, 3500, 2, 3, '2023-02-25', true, 'Alberta', 'Edmonton', 'Canada', '1295 Gecado Point', '96594');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Rhyme other', 'All tonight rear during earth consider nearest part even direct cool military cause parent easier slight great none swim thing month ahead attached complex grow up owner hurry teach tight everyone structure note dirty other plastic than provide shoot quietly balance money felt broke whale height forward move hold having condition horse therefore know disappear duck handsome agree cannot west shirt highway adult fact mice oil language melted section leather barn separate load fast crew usually nature rapidly note free safety slow add full wide girl harder movement term supply broad steel cold sister explain travel beyond begun adjective tax felt equator world noted dish able plenty leg moment opinion ready sand everywhere arrangement smallest long action reach quarter catch hair test thousand vast twenty friend travel little joined people sharp method share valuable smell subject statement nearest mouse break gave made afraid sum mean he frog muscle pole slowly breath local arm development double low funny parent over early get barn stiff crowd bush knife man material spend', 1, 'https://images.pexels.com/photos/2058692/pexels-photo-2058692.jpeg', 'https://images.pexels.com/photos/2058692/pexels-photo-2058692.jpeg?auto=compress&cs=tinysrgb&h=350', 62989, 2000, 6, 3, '2023-07-05', true, 'Northwest Territories', 'Town of Inuvik', 'Canada', '1190 Ozzow Ridge', '22036');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Remarkable date', 'Stronger aboard suppose diagram third fourth square river suppose brown phrase short ever business needed rope religious everything lot ship bat support torn face sit composed include hurt twelve occur angle myself compound shine small sugar sunlight care happen throat roof when baseball up service be wind within being tiny label practical easily learn find fellow pull second sent baseball die six wind suddenly eye stuck clearly right relationship tales frog happy surrounded ants rush are faster college blind charge adventure remarkable chance possibly meal neighborhood loose try wind faster but stop detail firm rocket if silent pony believed loud desert service seen percent wish medicine lesson attack coast soldier think cloud up voyage chicken hunter perfect local yesterday apple religious church comfortable burst clearly composed attached nearest joined struggle memory you very say satellites plant shade easy experiment twenty pale finish spider tobacco applied previous hundred crowd table ', 2, 'https://images.pexels.com/photos/2086639/pexels-photo-2086639.jpeg', 'https://images.pexels.com/photos/2086639/pexels-photo-2086639.jpeg?auto=compress&cs=tinysrgb&h=350', 2763, 5500, 9, 7, '2023-07-06', true, 'Alberta', 'Breton', 'Canada', '851 Heleze Heights', '30790');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code) 
    VALUES (
    'Student least', 'Win bridge breathe ruler on fog pocket rabbit also try wire ourselves additional matter lesson never tired explore lost beautiful attempt fire choose tail sets grandmother sudden iron classroom question his unhappy population planning young against accept gave bark quietly occasionally map vowel small family solar wash stretch husband describe attached here kill hearing lying ground melted pain maybe third memory worry slight difficulty way support slide source percent think point regular blind dirty nuts during nature became reach firm carry plastic modern although slightly magnet whispered stronger species waste hat beginning shop bigger fifteen behavior push dig dry whether ship guess equipment pretty dear highest between adventure fully however corner let proud welcome running ask eager wooden war broken gas joy every battle seed ', 3, 'https://images.pexels.com/photos/2079231/pexels-photo-2079231.jpeg', 'https://images.pexels.com/photos/2079231/pexels-photo-2079231.jpeg?auto=compress&cs=tinysrgb&h=350', 98264, 4500, 6, 6, '2022-09-29', true, 'Prince Edward Island', 'Souris', 'Canada', '242 Kinpa Grove', '36584');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, area, cost_per_month, number_of_bathrooms, number_of_bedrooms, created_at, active, province, city, country, street, post_code)
    VALUES (
    'Political every', 'Yet have shape feature finally replace former national lie block pupil invented plus wheel practical certain ordinary picture rays bag bank struggle direction naturally thirty football grain white source folks immediately road difficulty ill gently stranger frozen cabin voyage period cup managed attention volume red pretty consist them taught garden fifteen border think quick full shells passage peace loss please word unknown stronger unknown everything zero when plus instance lucky farmer better seat garage difficulty bent characteristic scale friend glass foot path buy high compound plus series fort printed nearest yet afternoon largest traffic gift whom wood quite walk search suppose neck amount contrast flame construction probably broke east excellent forget image put traffic is shop discuss season hay cannot region generally stage lonely ', 1, 'https://images.pexels.com/photos/2078875/pexels-photo-2078875.jpeg', 'https://images.pexels.com/photos/2078875/pexels-photo-2078875.jpeg?auto=compress&cs=tinysrgb&h=350', 9165, 1300, 6, 3, '2023-06-22', true, 'Saskatchewan', 'Tisdale', 'Canada', '831 Onaca Center', '39818');



INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_month, area, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active)
VALUES
  (1, 'Downtown Condo', 'A modern condo in downtown Toronto.bag bank struggle direction naturally thirty football grain white source folks immediately road difficulty ill gently stranger frozen cabin voyage period cup managed attention volume red pretty consist them taught garden fifteen border think quick full shells passage peace loss please word unknown stronger unknown everything zero when plus instance lucky farmer better seat garage difficulty bent characteristic scale friend glass foot path buy high compound plus series ', 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2982114084od-w480_h360_x2.jpg', 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3389156154od-w1024_h768_x2.jpg', 2200, 900, 2, 1, 'Canada', '123 King St', 'Toronto', 'ON', 'M5V 1J9', true);


INSERT INTO images (property_id, photo_url)
VALUES
  (2, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (2, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (2, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');




INSERT INTO images (property_id, photo_url)
VALUES
  (46, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (46, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (46, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');

  INSERT INTO images (property_id, photo_url)
VALUES
  (47, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (47, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (47, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');

  INSERT INTO images (property_id, photo_url)
VALUES
  (48, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (48, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (48, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');




INSERT INTO images (property_id, photo_url)
VALUES
  (49, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (49, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (49, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');

  INSERT INTO images (property_id, photo_url)
VALUES
  (50, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m2626392529od-w1024_h768_x2.jpg'),
  (50, 'https://ap.rdcpix.com/26999d161765fa2c5b56791f4ef93361l-m3838170680od-w1024_h768_x2.jpg'),
  (50, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80');
